# Render Blueprint configuration for Solana Volume Bot :cite[3]:cite[6]
services:
  - type: web
    name: solana-volume-bot
    runtime: node
    plan: free
    repo: https://github.com/your-username/solana-volume-bot
    branch: main
    buildCommand: npm install
    startCommand: node src/index.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: LOG_LEVEL
        value: info
      - key: DEFAULT_SOL_AMOUNT
        value: 0.1
      - key: DEFAULT_DURATION
        value: 60
      - key: DEFAULT_INTERVAL
        value: 30
      - key: SLIPPAGE_BPS
        value: 100
      # The following sensitive values should be set in Render Dashboard :cite[5]
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_USER_ID
        sync: false
      - key: SOLANA_WALLET_PRIVATE_KEY
        sync: false
      - key: SOLANA_RPC_URL
        value: https://api.mainnet-beta.solana.com
      - key: JUPITER_API_URL
        value: https://quote-api.jup.ag/v6
      - key: DEFAULT_TOKEN_ADDRESS
        sync: false

# Environment variables that need to be set in Render Dashboard:
# TELEGRAM_BOT_TOKEN=your_telegram_bot_token_here
# TELEGRAM_USER_ID=your_telegram_user_id
# SOLANA_WALLET_PRIVATE_KEY=[123,456,789,...] (as JSON array)
# DEFAULT_TOKEN_ADDRESS=your_default_token_address_here
